requires 'OX';

requires 'Plack';
requires 'Plack::Middleware::Static';
requires 'Path::Tiny';
requires 'Dir::Self';
requires 'HTML::Zoom';
requires 'MooseX::AttributeShortcuts';

requires 'DBD::Pg';
requires 'DBIx::Class';
requires 'DBIx::Class::Migration';
requires 'DBIx::Class::Candy';
requires 'Test::PostgreSQL';
requires 'DBIx::Class::InflateColumn::DateTime';
requires 'DBIx::Class::TimeStamp';

requires 'GeoIP2';
requires 'String::Trim';

requires 'MooX::Cmd';
requires 'MooX::Options';

requires 'Test::Most';
requires 'Test::PostgreSQL';
requires 'Test::Exception';
requires 'Test::DBIx::Class';
requires 'Test::BDD::Cucumber';
requires 'Test::WWW::Mechanize::PSGI';
